import Head from "next/head";
const Layout=({children})=>{
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="generated by create next app"></meta>
                <link rel="icon" href="/favicon.ico"></link>
            </Head>
        </>
    
)}