import Head from 'next/head'
import { pokeApi } from '../api'


export default function Home({pokemons}) {

  const origin = typeof window === "underfined" ? "" : window.location.origin;
  const layout = ({ children, title}) => {
   return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name= "author" content= "juan"></meta>
        <meta name="description" content="Generated by create next app" />
        <meta name= "keywords"> </meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>index</h1>
        {pokemons.map((pokemon) => (
          <div key={pokemon.id}>{pokemon.name}</div>

        ))}
       </main>

     
    </div>
  )
}
export const getStaticProps = async (ctx) => {
  const {data} = await pokeApi.get("/pokemon?limit=151") 
  const pokemons = data.results.map((poke, i) => ({
    ...poke,
    id: i+ 1,
    img: `https://raw.githubusercontent.con/PokeApi/sprites/master/sprites/pokemon/other/dream-world/${
      i + 1
    }.svg`,
    }));


  return {
    props:{
      pokemons,
    }
  } 
}